# Generated by Django 3.1.2 on 2020-11-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201106_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_data',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
    ]
