# Generated by Django 3.1.2 on 2020-11-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201119_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
