# Generated by Django 3.1.2 on 2020-11-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201120_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post_number',
            field=models.IntegerField(),
        ),
    ]
