# Generated by Django 3.1.2 on 2020-11-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201120_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
